exclude:
  - README.wiki
  - Capfile
  - config

url: http://hyip.github.io
name: The HYIP Project
topic: Project Introduction

path: /classes/project
remote_theme: eQ19/theme
permalink: /:categories/:title/

disqus_shortname: tophyips
google_analytics: UA-79558814-1
