# General Settings
# https://jekyllrb.com/docs/configuration/
# https://jekyllrb.com/docs/configuration/options/
# https://learn.cloudcannon.com/jekyll-cheat-sheet/

input_types:
- text
- date
- email
- radio
- number
- submit
- textarea
- checkbox

form_engines:
- formspree
- formbucket
- cloudcannon

debug:
  dist: false
  compress: false
  shortcodes: true

# Repository Settings
# https://blog.webjeda.com/jekyll-redirect/
# https://github.com/dotnet/docs/issues/20459#issuecomment-725295168
# https://github.com/ethanresnick/json-api-1/blob/gh-pages/_config.yml
# https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml

include:
  - app.js
  - feed.xml
  - feed.json
  - .htaccess
  - node_modules
  - package.json

exclude:
  - .babelrc
  - Makefile
  - yarn.lock
  - Dockerfile
  - Gemfile.lock
  - vendor/ruby/
  - vendor/gems/
  - vendor/cache/
  - vendor/bundle/
  - package-lock.json
  - webpack.config.js
  - docker_compose.yml
  - Makefile
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec

encoding: utf-8
livereload: true
limit_posts: 1000
collections_dir: maps
timezone: Asia/Jakarta
remote_theme: eQ19/parser
excerpt_separator: <!--end_excerpt-->

# Plugins Setting
# https://pages.github.com/versions/
# https://github.com/jekyll/jekyll-feed
# https://en.wikipedia.org/wiki/CoffeeScript
# https://github.com/jekyll/jekyll-redirect-from

plugins:
  - jemoji
  - jekyll-gist
  - jekyll-feed
  - jekyll-avatar
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-coffeescript
  - jekyll-redirect-from

whitelist:
  - jemoji
  - jekyll-gist
  - jekyll-feed
  - jekyll-avatar
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-coffeescript
  - jekyll-redirect-from
  
# Default Setting
# https://stackoverflow.com/a/49428493
# https://jekyllrb.com/docs/collections/
# https://chetabahana.github.io/app/flowchart.json
# https://jekyllrb.com/docs/configuration/front-matter-defaults

defaults:
  -
    scope:
      path: ""
      type: "feeds"
    values:
      layout: "feeds"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "leads"
    values:
      layout: "redirect"

# Permalinks
# https://jekyllrb.com/docs/permalinks/
# feeds: https://chetabahana.github.io/main/tree.json
# leads: https://chetabahana.github.io/leads/section.json
# posts: https://chetabahana.github.io/object/2018/132/05/00/00/00/dummy.json

collections:
  leads:
    output: true
  feeds:
    output: true
    permalink: /:categories/:title:output_ext
  posts:
    permalink: /:categories/:year/:y_day/:month/:hour/:minute/:second/:title:output_ext

# Feed Setting
# https://github.com/jekyll/jekyll-feed/issues/2
# https://www.w3schools.com/xml/xsl_elementref.asp
# https://github.com/jekyll/jekyll-feed/issues/207#issuecomment-787490785

feed:
  tags: true
  posts_limit: 1000
  excerpt_only: true
  collections:
    leads:
      path: /leads.xml # https://chetabahana.github.io/leads.xml
    feeds:
      categories:
        - main # https://chetabahana.github.io/feed/feeds/main.xml
        - user # https://chetabahana.github.io/feed/feeds/user.xml
        - diagram # https://chetabahana.github.io/feed/feeds/diagram.xml
        - section # https://chetabahana.github.io/feed/feeds/section.xml
      path: /feeds.xml # https://chetabahana.github.io/feeds.xml

# Kramdown Options
# https://kramdown.gettalong.org/options.html
# https://jekyllrb.com/docs/configuration/markdown/

highlighter: rouge
markdown: kramdown

kramdown:
  html_to_native: true
  syntax_highlighter: pygments
  math_engine_opts configuration: mathjax
 
# Custom Headers
# https://shopify.github.io/liquid/
# https://jekyllrb.com/docs/configuration/webrick/
# https://en.wikipedia.org/wiki/Content_Security_Policy

google:
  gtag: GTM-PGWT4RS
  #adsense: ca-pub-3677197599836940
webrick:
  headers:
    Content-Security-Policy: default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self';
    #My-Other-Header: My-Other-Value
#sumo: 2b0c75104f236f75954a2d200c80651a1ebf311e7f2c868ac12d7284ecd4fbd4

# Tags Setting
# http://codinfox.github.io/blog/tags/
# https://longqian.me/2017/02/09/github-jekyll-tag/
# https://github.com/chetabahana/chetabahana.github.io/tags

case_labels:
- Buka Toko
- Stok Barang
- Merchant Center
- Peluang Terbaik
- Portfolio
- Network

flow_labels:
- Optimasi
- Cloud-Task-API
- Cloud-Site-API
- Google-Ads-API
- Google-Trend-API
- eShop SEO

# Site Setting
# https://jekyllrb.com/docs/variables/
# https://stackoverflow.com/a/17260660/4058484
# https://stackoverflow.com/a/30828197/4058484

username: eq19
basedir: _feeds
organization: feedmapping
repository: eq19/eq19.github.io
project_link: https://www.eq19.com/

# Site Metadata
# https://stackoverflow.com/a/55094996/4058484
# https://help.github.com/articles/repository-metadata-on-github-pages/
# https://www.google.com/search?q=tortoisegit+keep+asking+password+site%3Astackoverflow.com
# https://stackoverflow.com/questions/3490505/is-there-a-notepad-with-github-plugin/41884020
# https://stackoverflow.com/questions/14000173/tortoisegit-save-user-authentication-credentials
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll

title: ₠Quantum
license: Apache License, Version 2.0
name: ₠Quantum Project | A Unique Mapping System
slogan: ₠Quantum Project | System Mapping and Definition
disclaimer: The definite key to identify whether you use our concept is when there a kind of development item lies a unified assignment in hexagonal form by six (6) corresponding sets while each sets pick a combination of six (6) routes with a pairing of six (6) to six (6) of all channels.
